# Generated by Django 4.2 on 2023-04-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_questions_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
